config/routes.rb
Rails.application.routes.draw do

  get 'debug', to: 'debug#index'
  post 'debug', to: 'debug#add'
  get 'debug/delete/:id', to: 'debug#delete'
  post '/submit/analysis/:str', to: 'submit#handler'
  get '/submit/analyses/:id', to: 'submit#analyses'


  resources :projects do
    resources :samples do
      collection do
        post :import
        post :import_inf_table
      end
      member do
        post :upload_seq
        post :upload_inf
        get :download_seq
        get :download_inf
      end
    end
    collection { post :import}
    collection { post :download_selected_file }
    collection { post :export_selected }
    member { post :download_inf_table}
    member { post :show, format: 'json' }

  end

  resources :samples do
    collection do
      post :make_selected_file
    end
  end

  resources :organs do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :cancers do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :users do
    resources :datasets do
      member { post :upload_file }
      member { get :download_file}
      member { get :download_ds_inf}
      member { get :download_ds_metadata}
      member { post :delete_sample}
    end
  end
  
  root 'welcome#index'

  get 'tutorial', to: 'welcome#tutorial', as: 'tutorial'
  get '/tutorial/database/1', to: "tutorial#database1"
  get '/tutorial/database/2', to: "tutorial#database2"
  get '/tutorial/database/3', to: "tutorial#database3"
  get '/tutorial/database/4', to: "tutorial#database4"


  get '/tutorial/analysis/1', to: "tutorial#analysis1"
  get '/tutorial/analysis/2', to: "tutorial#analysis2"
  get '/tutorial/analysis/3', to: "tutorial#analysis3"
  get '/tutorial/analysis/4', to: "tutorial#analysis4"
  get '/tutorial/mub', to: "tutorial#mub"




  get 'contact', to: 'welcome#contact', as: 'contact'
  get 'docs', to: redirect('docs/index.html')
  get 'terms', to: 'welcome#terms', as: 'terms'

  # read local csv file 
  # get 'data/:name', to: 'raw_files#index'
  get 'api/local', to: 'raw_files#index'
  get 'api/public', to: 'raw_files#public'

  # draw on overview page
  namespace :api do
    resources :analysis, only: [] do
      get 'use_demo', to: 'viz_files#use_demo', as: 'use_demo'
      get 'use_task_output', to: 'viz_files#use_task_output', as: 'use_task_output'
      get 'all_files', to: 'viz_files#all_files', as: 'all_files'
      get 'all_task_outputs', to: 'viz_files#all_task_outputs', as: 'all_task_outputs'
      get 'chosen_files', to: 'viz_files#get_chosen_files', as: 'chosen_files'
      get 'chosen_file_paths', to: 'viz_files#chosen_file_paths', as: 'chosen_file_paths'
      get 'download_demo_file', to: 'viz_files#download_demo_file', as: 'download_demo_file'
      post 'chosen_files', to: 'viz_files#update_chosen_files', as: 'update_chosen_files'
      post 'create_files', to: 'viz_files#create_files', as: 'create_files'
      post 'batch_delete_files', to: 'viz_files#batch_delete_files', as: 'batch_delete_files'
    end
    get "public_file/check_file_exists", to: 'public_file#check_file_exists', as: 'json'
    get 'tabix/:url_name', to: 'tabix_apis#show', as: 'tabix_api'
    get 'public/:url_name', to: 'public_file_apis#show', as: 'public_api'
    get "download_target_file", to: "public_file#download_target_file", as: 'download_target_file'
  end

  # database pages
  get 'database/overview', to: 'database#overview'
  get '/download', to: 'welcome#download'

  get 'user/show', to: 'users#show'
  # get 'demo', to: 'demo#show'
  #post 'welcome/accept_cookies', to: 'welcome#require_cookie'
  post "welcome/require_cookie", to: "welcome#require_cookie", as: "require_cookie"
  
  # visualizer
  scope '/visualizer' do
    # resources :analysis, except: :index
    get 'analysis/:url_name', to: 'analysis#show', as: 'analysis'
  end
  get 'visualizer', to: "analysis#index", as: "visualizer"


  # submit pages
  get "submit/analyses", to: "submit#analyses"
  get "submit/analysesCategory", to: "submit#analysesCategory"
  get "submit/tcrAnalyses", to: "submit#tcrAnalyses"
  get "submit/tcrclub", to: "submit#tcrclub"

  get "submit/pipelines", to: "submit#pipelines"
  get 'submit/job-query/', to: 'submit#query', as: 'query'
  get 'submit/job-query-demo', to: 'submit#query_demo', as: 'query-demo'

  get "submit/job-demo", to: "submit#demo"
  get 'submit/analysis/:id', to: 'submit#index', as: 'submit_analysis'
  get 'submit/pipeline/:id', to: 'submit#pipeline', as: 'submit_pipeline'
  post 'change_dark', to:'application#change_dark'

  post 'query-app-task', to: 'submit#query_app_task', format: 'json'
    post 'query-app-task-dummy', to: 'submit#query_app_task_dummy'
  post 'query-demo-tasks', to: 'submit#query_demo_tasks', format: 'json'
  post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  post 'query-demo-task', to: 'submit#query_demo_task', format: 'json'
  post 'query-all-tasks', to: 'submit#query_all', format: 'json'
  post 'remove-task', to: 'submit#remove_task', format: 'json'

  # get "debug", to: "submit#query_app_task_test"
  # post 'query_app_task_dummy', to: 'submit#query_app_task_dummy'
  # post 'submit_app_task_dummy', to: 'submit#submit_app_task_dummy'
  # post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  # post 'submit-app-task-dummy', to: 'submit#submit_app_task_dummy', format: 'json'

  # admin
  get '/admin', to: 'admin#index', as: "admin_index"
  post "admin/modify_sample_metadata" => "admin#modify_sample_metadata", :as => "admin/modify_sample_metadata"
  post "admin/modify_sample_inf" => "admin#modify_sample_inf", :as => "admin/modify_sample_inf"
  post "admin/update_samples_num_table_and_reprocessedColumns" => "admin#update_samples_num_table_and_reprocessedColumns", :as => "admin/update_samples_num_table_and_reprocessedColumns"
  post "admin/make_analysis_cancer_files" => "admin#make_analysis_cancer_files", :as => "admin/make_analysis_cancer_files"
  post "admin/make_subtype_cancer_files" => "admin#make_subtype_cancer_files", :as => "admin/make_subtype_cancer_files"
  post "admin/update_columns" => "admin#update_columns", :as => "admin/update_columns"
  post "admin/update_files" => "admin#update_files", :as =>"admin/update_files"
  post "admin/count_rna_samples" => "admin#count_rna_samples", :as =>"admin/count_rna_samples"
  post "admin/update_columns_cancer" => "admin#update_columns_cancer", :as => "admin/update_columns_cancer"

  post "admin/modify_viz" => "admin#modify_viz", :as => "admin/modify_viz"
  post "admin/modify_ana_cate" => "admin#modify_ana_cate", :as => "admin/modify_ana_cate"
  post "admin/modify_ana" => "admin#modify_ana", :as => "admin/modify_ana"
  post "admin/modify_viz_source" => "admin#modify_viz_source", :as => "admin/modify_viz_source"
  post "admin/add_img" => "admin#add_img", :as => "admin/add_img"
  post "admin/delete_samples" => "admin#delete_samples", :as => "admin/delete_samples"
  post "admin/update_all_samples" => "admin#update_all_samples", :as => "admin/update_all_samples"
  post "admin/update_all_organs" => "admin#update_all_organs", :as => "admin/update_all_organs"
  post "admin/update_all_cancers" => "admin#update_all_cancers", :as => "admin/update_all_cancers"



  namespace :admin do
    post :update_analysis_category_position, to: 'analysis_categories#update_position'
    resources :analysis_categories, except: :show do
      post :update_position, to: 'analyses#update_position', as: 'update_analysis_position'
      resources :analyses, expect: %i[index show]
    end
    get 'analyses', to: 'analyses#index'
    resources :visualizers
    resources :analysis_pipelines
    resources :tasks, except: :new
    post "clear_outputs", to:"tasks#clear_outputs", as: "clear_outputs"
    post "set_demo_task", to:"tasks#set_demo_task", as: "set_demo_task"
    resources :file_keys, except: :show
    resources :tabix_apis, except: :show
  end

  # serve files
  match 'data/uploads/*path', to: 'raw_files#uploads', as: 'get_uploads', via: :get
  match 'data/demo/*path', to: 'raw_files#demo', as: 'get_demo', via: :get
  match 'data/outputs/*path', to: 'raw_files#outputs', as: 'get_outputs', via: :get
  match 'data/static_viz_data/*path', to: 'raw_files#viz_file', via: :get
  match 'public/data/*path', to: 'raw_files#public_file', via: :get
  match 'public/data/sample_plot/*path', to: 'raw_files#viz_inf_file', via: :get
  get "/database/refreshSelector", to: 'database#refreshSelector'

  post 'query-deepomics', to: 'submit#query_deepomics', format: 'json'
  post 'task-details', to: 'submit#task_details', format: 'json'



end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :project
  has_and_belongs_to_many :datasets
  validates :sample_name, presence: true, uniqueness: { 
    message: ->(object, data) do
      "Sample #{data[:value]} already exists. "
    end
  }, on: :create

  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |sample|
        csv << sample.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.selected_to_csv(sample_ids, options={})
    CSV.generate(options) do |csv|
      csv << column_names
      sample_ids.each do |id|
        sample = Sample.find(id)
        csv << sample.attributes.values_at(*column_names)
      end
    end
  end


  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'bom|utf-8') do |row|
      sample = find_by_sample_name(row['sample_name'])|| new
      sample.attributes = row.to_hash.slice(*column_names)
      pname = sample.project_name
      project = Project.find_by(project_name: pname)
      sample.project_id = project.id
      cancer = Cancer.find(project.cancer_id)
      # Rails.logger.info "Outputing cancer name:"
      # Rails.logger.info sample.cancer_name
      # sample.cancer_name = cancer.cancer_name
      project.update_attribute(:num_of_samples, project.samples.count)
      sample.save!
    end
  end

  def self.selected_inf_to_tsv(ids, option={})
    len = ids.length() # number of the samples
    if len<1
      return ""
    else
      out_json = {}
      ids.each_with_index do |id, index|

        @sample = Sample.find(id)
        @project = Project.find(@sample.project_id)
        n1 = @project.project_name
        n2 = @sample.sample_name
        file_current = "#{$inf_dir}#{n1}_#{n2}.tsv"
        i = index
        if (File.file?(file_current)) 
          File.readlines(file_current).each_with_index do |line, index2| 
            if index2 >0 
              contents = line.split("\t")
              k = contents[0].chomp
              v = contents[1].chomp
              if !(out_json.key?(k))
                out_json[k] = Array.new(len, 0.0) 
              end
              out_json[k][i] = v.to_f 
            end
          end
        end
      end
      if option != {} && option["pj_name"]
        lefttop_name = option["pj_name"]
      else
        lefttop_name = 'selected'
      end
      keys = out_json.keys

      s1 = "#{lefttop_name}"
      ids.each_with_index do |id, index|
        @sample = Sample.find(id)
        s_name = @sample.sample_name
        s1 += "\t#{s_name}"
      end

      keys.each do |key|
        s1 += "\n"
        s1 += "#{key}"
        i = 0
        while i<len
          v = out_json[key][i]
          s1 += "\t#{v}"
          i = i+1
        end
      end

      return s1
    end
  end 

  def self.filtered(keyword, project=nil)
    search_string = []
    Sample.column_names.each do |attr|
      if Sample.columns_hash[attr].type != :string
        search_string << "cast(\"#{attr}\" as varchar(10)) like :search"
      else
        search_string << "\"#{attr}\" like :search"
      end
    end

    if(project!= nil)
      samples = project.samples.order(:sample_name)
      samples = samples.where(search_string.join(' or '), search: "%#{keyword}%")
      
    else
      samples = Sample.order(:sample_name)
      samples = samples.where(search_string.join(' or '), search: "%#{keyword}%")
      
    end
    ids = samples.ids


    return ids
  end

end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_for([@project, @sample]) do |f| %>

  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@sample.errors.count, "error") %> prohibited
        this sample from being saved:
      </h2>
      <ul>
        <% @sample.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <% @sample_attrs.each do |attr| %>
    <% if attr != 'id' && attr != 'created_at' && attr != 'updated_at' %>
      <p> 
        <%= f.label attr.capitalize %> <br>
        <%= f.text_field attr %>
      </p>

    <% end %>
  <% end %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/samples/_sample.html.erb
<p>
    <strong>Sample:</strong>
    <%= sample.sample_name %>
</p>
 
<p>
    <strong>Project:</strong>
    <%= sample.project_name %>
</p>

<p>
    <strong>Age:</strong>
    <%= sample.host_age %>
</p>
  
<p>
    <%= link_to 'Edit', edit_project_sample_path(sample.project, sample.id) %> 
    <%= link_to 'Delete', [sample.project, sample],
    method: :delete,
    data: { confirm: 'Are you sure to delete ' + sample.sample_name + '?'} %>
</p>

app/views/samples/edit.html.erb
<div class="container">
    <h1>Edit Sample</h1>
    
    <%= render 'samples/form' %>
    <%= link_to 'Back', "/admin" %>
</div>

app/views/samples/index.html.erb
<% content_for:head do%>

  
  <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/fixedcolumns/3.3.2/js/dataTables.fixedColumns.min.js"></script>

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/3.3.2/css/fixedColumns.dataTables.min.css">
  
  <%= javascript_pack_tag "datatable" %>
<%end%>
<% content_for :title, 'Samples' %>
<div class="container">
    <div class="mt-5">
      <h1>
      Samples Information
      <button class = "btn btn-1" style="display:inline" >
        <%= link_to "Database Helper", "tutorial" %>
      </button>
      </h1>
    </div>
  <br/>



                                            <div id="db-toolbar" class="mb-5">
                                              <div class="db-tool-nav">

                                                <div class="btn btn-outline-dark" data-toggle="collapse" data-target="#download_box" aria-expanded="true" aria-controls="download_box">
                                                  Download Table Data <i class="fas fa-caret-down"></i>
                                                </div>
                                                <div class="btn btn-outline-dark" data-toggle="collapse" data-target="#export_box" aria-expanded="true" aria-controls="export_box">
                                                  Export samples to Dataset <i class="fas fa-caret-down"></i>
                                                </div>
                                              </div>

                                              <%= form_tag make_selected_file_samples_path, multipart: true do %>
                                                
                                                <div id="download_box" class="db-toolbox collapse" data-parent="#db-toolbar">
                                                  <div class="form-group p-2">
                                                    <%= button_tag :name => 'download_select', disabled: true, 
                                                      :class => "s_table_sub btn btn-secondary btn-select download" do %>
                                                      <i class='fas fa-check-circle'></i> Selected samples
                                                    <%end%>
                                                    <%= button_tag :name => 'download_filter',
                                                      :class => "s_table_sub btn btn-theme btn-info btn-search download", disabled: true do %>
                                                      <i class='fas fa-filter'></i> Searched samples
                                                    <%end%>
                                                    <%= button_tag :class => "s_table_sub btn btn-pink" do %>
                                                      <%= link_to samples_path(format: "csv") do %>
                                                        <i class='fas fa-download'></i> All samples
                                                      <% end %>
                                                    <%end%>
                                                  </div>
                                                  <p> With over 1,500 samples, please directly download all samples.</p>
                                                </div>
                                                <div id="export_box" class="db-toolbox collapse"  data-parent="#db-toolbar">
                                                  <div class="form-group p-2">
                                                    <%= button_tag :name => 'seleted2ds', disabled: true, 
                                                      :class => "s_table_sub btn btn-select btn-theme export-db" do %>
                                                      <i class='fas fa-check-circle'></i> Selected samples
                                                    <%end%>
                                                    <%= button_tag :name => 'filter2ds', disabled: true, 
                                                        :class => "s_table_sub btn btn-search btn-pink export-db" do %>
                                                      <i class='fas fa-filter'></i> Searched samples
                                                    <%end%>
                                                    <span class="btn ml-3">to your dataset:</span>
                                                    <select id="select_box" class="btn btn-outline-secondary" name="ds_selected">
                                                      <option value="">--Please choose a dataset--</option>
                                                      <% @datasets.each do |ds|%>
                                                        <option value="<%=ds.name%>"> <%=ds.name%></option>
                                                      <%end%>
                                                    </select>
                                                  </div>
                                                  <p>
                                                    If you do NOT have any dataset yet, please create one here: 
                                                    <%=link_to 'Create new dataset', new_user_dataset_path(:user_id=>@user.id)%>
                                                  </p>
                                                </div>
                                              <%end%>
                                            </div>







  <%= form_tag make_selected_file_samples_path,class:(session[:dark] ? "dark-table mb-4": "mb-4"), multipart: true do %>
    <%= content_tag :table, role: :datatable, class: "display", id: "table_page", data: { url: samples_path(format: :json)} do %>
      <p>You can click <span style= "color: #006fff;">sample name</span> to view the original link of samples。
      You can click <span style= "color: #006fff;">details</span> to view the detailed information for samples.
      </p>
      <thead>
            <th>
              <input type="checkbox" class="selectAll" name="selectAll" value="all"> 
            </th>
            <% @sample_attrs.each do |attr| %>
              <% attr = attr.gsub(/^n_/, "") %>
              <% attr = attr.gsub(/^c_/, "") %>
              <th> <%= attr %> </th>
            <% end %>
            <th>details</th>
      </thead>
      <tbody></tbody>
    <% end %>

    
    
  <% end %>


</div>

app/views/samples/new.html.erb
<h1> New sample </h1>
<%= render 'form'%>
<%= link_to 'Back', '/admin' %>

app/views/samples/show.html.erb
<% content_for :title, 'Sample ' + @sample.sample_name %>
<div class="container">

    <h2 class = "mt-5">
    Sample Information
    </h2>

    <br>
    
    <div id="detail_box">
        <div class="d-flex">
        <% @short_attrs.each do |attrs| %>
            <div class="w-50">
            <table class="detail-table table table-bordered table-sm">
                <% attrs.each do |attr| %>
                <tr>
                    <% dis_attr = attr %>
                    <% dis_attr = dis_attr.gsub(/^n_/, "") %> 
                    <% dis_attr = dis_attr.gsub(/^c_/, "") %> 
                    <td class="label"><%= dis_attr %></td>
                    <td>
                    <%= @sample[attr] %>
                    </td>
                </tr>
                <% end %>
            </table>
            </div>
        <% end %>
        </div>
    </div>
    <br />

    <div class = "container ">



        <%if @inf_exist %>
            <div id="db-toolbar" class="mb-5">
                <div class="db-tool-nav">

                    <div class="btn btn-outline-dark" data-toggle="collapse" data-target="#download_box" aria-expanded="true" aria-controls="download_box">
                        Download <i class="fas fa-caret-down"></i>
                    </div>
                    <div id="download_box" class="db-toolbox collapse" data-parent="#db-toolbar">
                            <div class="form-group p-2">
                                <%= button_tag :class => "s_table_sub btn btn-pink" do %>
                                    <%= link_to download_inf_project_sample_path do %>
                                        <i class='fas fa-download'></i>deconvolution result
                                    <% end %>
                                <%end%>
                                <%= button_tag :name => 'download_filter', :id => "download_chart",
                                    :class => "s_table_sub btn btn-search btn-theme download"  do %>
                                    <i class='fas fa-filter'></i> download chart
                                    <%end%>
                            </div>
                    </div>
                </div>
            </div>

            <div id="viz_sample_inf" class = "">
            </div>
            <%= javascript_pack_tag "static_inf" %>
        <% else %>
            <h2> * This sample only provides the clinical data. </h2>
        <%end%>
    </div>
    
</div>
    