config/routes.rb
Rails.application.routes.draw do

  get 'debug', to: 'debug#index'
  post 'debug', to: 'debug#add'
  get 'debug/delete/:id', to: 'debug#delete'
  post '/submit/analysis/:str', to: 'submit#handler'
  get '/submit/analyses/:id', to: 'submit#analyses'


  resources :projects do
    resources :samples do
      collection do
        post :import
        post :import_inf_table
      end
      member do
        post :upload_seq
        post :upload_inf
        get :download_seq
        get :download_inf
      end
    end
    collection { post :import}
    collection { post :download_selected_file }
    collection { post :export_selected }
    member { post :download_inf_table}
    member { post :show, format: 'json' }

  end

  resources :samples do
    collection do
      post :make_selected_file
    end
  end

  resources :organs do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :cancers do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :users do
    resources :datasets do
      member { post :upload_file }
      member { get :download_file}
      member { get :download_ds_inf}
      member { get :download_ds_metadata}
      member { post :delete_sample}
    end
  end
  
  root 'welcome#index'

  get 'tutorial', to: 'welcome#tutorial', as: 'tutorial'
  get '/tutorial/database/1', to: "tutorial#database1"
  get '/tutorial/database/2', to: "tutorial#database2"
  get '/tutorial/database/3', to: "tutorial#database3"
  get '/tutorial/database/4', to: "tutorial#database4"


  get '/tutorial/analysis/1', to: "tutorial#analysis1"
  get '/tutorial/analysis/2', to: "tutorial#analysis2"
  get '/tutorial/analysis/3', to: "tutorial#analysis3"
  get '/tutorial/analysis/4', to: "tutorial#analysis4"
  get '/tutorial/mub', to: "tutorial#mub"




  get 'contact', to: 'welcome#contact', as: 'contact'
  get 'docs', to: redirect('docs/index.html')
  get 'terms', to: 'welcome#terms', as: 'terms'

  # read local csv file 
  # get 'data/:name', to: 'raw_files#index'
  get 'api/local', to: 'raw_files#index'
  get 'api/public', to: 'raw_files#public'

  # draw on overview page
  namespace :api do
    resources :analysis, only: [] do
      get 'use_demo', to: 'viz_files#use_demo', as: 'use_demo'
      get 'use_task_output', to: 'viz_files#use_task_output', as: 'use_task_output'
      get 'all_files', to: 'viz_files#all_files', as: 'all_files'
      get 'all_task_outputs', to: 'viz_files#all_task_outputs', as: 'all_task_outputs'
      get 'chosen_files', to: 'viz_files#get_chosen_files', as: 'chosen_files'
      get 'chosen_file_paths', to: 'viz_files#chosen_file_paths', as: 'chosen_file_paths'
      get 'download_demo_file', to: 'viz_files#download_demo_file', as: 'download_demo_file'
      post 'chosen_files', to: 'viz_files#update_chosen_files', as: 'update_chosen_files'
      post 'create_files', to: 'viz_files#create_files', as: 'create_files'
      post 'batch_delete_files', to: 'viz_files#batch_delete_files', as: 'batch_delete_files'
    end
    get "public_file/check_file_exists", to: 'public_file#check_file_exists', as: 'json'
    get 'tabix/:url_name', to: 'tabix_apis#show', as: 'tabix_api'
    get 'public/:url_name', to: 'public_file_apis#show', as: 'public_api'
    get "download_target_file", to: "public_file#download_target_file", as: 'download_target_file'
  end

  # database pages
  get 'database/overview', to: 'database#overview'
  get '/download', to: 'welcome#download'

  get 'user/show', to: 'users#show'
  # get 'demo', to: 'demo#show'
  #post 'welcome/accept_cookies', to: 'welcome#require_cookie'
  post "welcome/require_cookie", to: "welcome#require_cookie", as: "require_cookie"
  
  # visualizer
  scope '/visualizer' do
    # resources :analysis, except: :index
    get 'analysis/:url_name', to: 'analysis#show', as: 'analysis'
  end
  get 'visualizer', to: "analysis#index", as: "visualizer"


  # submit pages
  get "submit/analyses", to: "submit#analyses"
  get "submit/analysesCategory", to: "submit#analysesCategory"
  get "submit/tcrAnalyses", to: "submit#tcrAnalyses"
  get "submit/tcrclub", to: "submit#tcrclub"

  get "submit/pipelines", to: "submit#pipelines"
  get 'submit/job-query/', to: 'submit#query', as: 'query'
  get 'submit/job-query-demo', to: 'submit#query_demo', as: 'query-demo'

  get "submit/job-demo", to: "submit#demo"
  get 'submit/analysis/:id', to: 'submit#index', as: 'submit_analysis'
  get 'submit/pipeline/:id', to: 'submit#pipeline', as: 'submit_pipeline'
  post 'change_dark', to:'application#change_dark'

  post 'query-app-task', to: 'submit#query_app_task', format: 'json'
    post 'query-app-task-dummy', to: 'submit#query_app_task_dummy'
  post 'query-demo-tasks', to: 'submit#query_demo_tasks', format: 'json'
  post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  post 'query-demo-task', to: 'submit#query_demo_task', format: 'json'
  post 'query-all-tasks', to: 'submit#query_all', format: 'json'
  post 'remove-task', to: 'submit#remove_task', format: 'json'

  # get "debug", to: "submit#query_app_task_test"
  # post 'query_app_task_dummy', to: 'submit#query_app_task_dummy'
  # post 'submit_app_task_dummy', to: 'submit#submit_app_task_dummy'
  # post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  # post 'submit-app-task-dummy', to: 'submit#submit_app_task_dummy', format: 'json'

  # admin
  get '/admin', to: 'admin#index', as: "admin_index"
  post "admin/modify_sample_metadata" => "admin#modify_sample_metadata", :as => "admin/modify_sample_metadata"
  post "admin/modify_sample_inf" => "admin#modify_sample_inf", :as => "admin/modify_sample_inf"
  post "admin/update_samples_num_table_and_reprocessedColumns" => "admin#update_samples_num_table_and_reprocessedColumns", :as => "admin/update_samples_num_table_and_reprocessedColumns"
  post "admin/make_analysis_cancer_files" => "admin#make_analysis_cancer_files", :as => "admin/make_analysis_cancer_files"
  post "admin/make_subtype_cancer_files" => "admin#make_subtype_cancer_files", :as => "admin/make_subtype_cancer_files"
  post "admin/update_columns" => "admin#update_columns", :as => "admin/update_columns"
  post "admin/update_files" => "admin#update_files", :as =>"admin/update_files"
  post "admin/count_rna_samples" => "admin#count_rna_samples", :as =>"admin/count_rna_samples"
  post "admin/update_columns_cancer" => "admin#update_columns_cancer", :as => "admin/update_columns_cancer"

  post "admin/modify_viz" => "admin#modify_viz", :as => "admin/modify_viz"
  post "admin/modify_ana_cate" => "admin#modify_ana_cate", :as => "admin/modify_ana_cate"
  post "admin/modify_ana" => "admin#modify_ana", :as => "admin/modify_ana"
  post "admin/modify_viz_source" => "admin#modify_viz_source", :as => "admin/modify_viz_source"
  post "admin/add_img" => "admin#add_img", :as => "admin/add_img"
  post "admin/delete_samples" => "admin#delete_samples", :as => "admin/delete_samples"
  post "admin/update_all_samples" => "admin#update_all_samples", :as => "admin/update_all_samples"
  post "admin/update_all_organs" => "admin#update_all_organs", :as => "admin/update_all_organs"
  post "admin/update_all_cancers" => "admin#update_all_cancers", :as => "admin/update_all_cancers"



  namespace :admin do
    post :update_analysis_category_position, to: 'analysis_categories#update_position'
    resources :analysis_categories, except: :show do
      post :update_position, to: 'analyses#update_position', as: 'update_analysis_position'
      resources :analyses, expect: %i[index show]
    end
    get 'analyses', to: 'analyses#index'
    resources :visualizers
    resources :analysis_pipelines
    resources :tasks, except: :new
    post "clear_outputs", to:"tasks#clear_outputs", as: "clear_outputs"
    post "set_demo_task", to:"tasks#set_demo_task", as: "set_demo_task"
    resources :file_keys, except: :show
    resources :tabix_apis, except: :show
  end

  # serve files
  match 'data/uploads/*path', to: 'raw_files#uploads', as: 'get_uploads', via: :get
  match 'data/demo/*path', to: 'raw_files#demo', as: 'get_demo', via: :get
  match 'data/outputs/*path', to: 'raw_files#outputs', as: 'get_outputs', via: :get
  match 'data/static_viz_data/*path', to: 'raw_files#viz_file', via: :get
  match 'public/data/*path', to: 'raw_files#public_file', via: :get
  match 'public/data/sample_plot/*path', to: 'raw_files#viz_inf_file', via: :get
  get "/database/refreshSelector", to: 'database#refreshSelector'

  post 'query-deepomics', to: 'submit#query_deepomics', format: 'json'
  post 'task-details', to: 'submit#task_details', format: 'json'



end

app/views/admin/index.html.erb
<% content_for:head do%>
  
  <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <%= javascript_pack_tag "table_style" %>
  
<%end%>

<% content_for :title, "Admin" %>

<div class="container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%=link_to 'Admin home', '/admin' %>
    </li> 
    <li class="breadcrumb-item">
      <%=link_to 'Datasets', '#project_admin' %>
    </li> 
    <li class="breadcrumb-item">
      <%=link_to 'Samples', '#sample_admin' %>
    </li> 
    <li class="breadcrumb-item">
      <%=link_to 'Cancers', '#cancer_admin' %>
    </li> 
    <li class="breadcrumb-item">
      <%=link_to 'Analysis Categories', admin_analysis_categories_path %>
    </li> 
    <li class="breadcrumb-item">
      <%=link_to 'Analyses', admin_analyses_path %>
    </li> 
    <li class="breadcrumb-item">
      <%=link_to 'tasks', admin_tasks_path %>
    </li> 
  </ol>


  <h1>
  Admin page
  </h1>

  <p>
      This is made for admin to :
      <ul>
        <li>add project metadata</li>
        <li>add sample metadata</li>
        <li>add cancer type metadata</li>
        <li>add sample abandance data</li>
        <li>add analysis module</li>
        <li>add visualization module</li>
      </ul>
  </p>

  <hr />


  <br />

  <section id="project_admin" class="admin_block">
    <h4>
    Project management:
    </h4>

    
    <div id="table">
      <table class="display" >
        <thead>
          
          <% @projects.column_names.each do |attr| %>
            
            <th> <%= attr.capitalize %> </th>
            
          <% end %>
          <th>
            Action
          </th>
          
        </thead>

        <tbody>
          <% @projects.each do |pj| %>
          
            <tr>
              <% @projects.column_names.each do |attr| %>
                
                <td> 
                  <div class="table_cell"> 
                    <%= pj[attr] %> 
                  </div>
                </td>
              
              <% end %>
              <td>
                <%= link_to 'Show', project_path(pj) %>
                <%= link_to 'Delete', project_path(pj), method: :delete,
                        data: { confirm: 'Are you sure?' } %>

                <%= link_to 'Edit', edit_project_path(pj) %>
              </td>
              
            </tr>
          
          <% end %>
        </tbody>

      </table>
    </div>
    <%= link_to  "Add one project", "/projects/new" %>

    <%= form_tag import_projects_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import projects from csv" %>
    <% end %>
  </section>
  <hr />

  <section id="sample_admin" class="admin_block">
    <h4>
    Sample management:
    </h4>
    <br />
    <h5>
      Import all sample metadata from csv:
    </h5>

    <%= form_tag({action: :update_all_samples}, multipart: true) do %>
      <p> 
        Please select csv file to be imported:
        <br />
        (project_name should exist in projects database )
      </p>
      <%= file_field_tag 'file' %>
      <%= submit_tag 'Submit'%>
    <% end %>
    <br/>
    <h5>
      Delete samples:
    </h5>

    <%= form_tag({action: :delete_samples}, multipart: true) do %>
      <p> 
        Please select csv file to be imported:
        <br />
        (samples id in a column)
      </p>
      <%= file_field_tag 'file' %>
      <%= submit_tag 'Submit'%>
    <% end %>
    <br />


    <h5>
      Modify the immune infiltration data:
    </h5>

    <%= form_tag({action: :modify_sample_inf}, multipart: true) do %>
      <p>
        Please select the project whose samples need to be modified
      </p>
      <%= select_tag :project_id, options_from_collection_for_select(@projects, :id, :project_name, -1) %>
      <p> 
        Please select tsv file to be imported:
      </p>
      <%= file_field_tag 'file' %>
      <%= submit_tag 'Submit'%>
    <% end %>
  </section>



   <hr />
   
  <section id="cancer_admin" class="admin_block">
    <h4>
    Cancer type management:
    </h4>

    <div id='hidden_helper'>
    Hide columns: 
    <br />
    <% i=0 %>
    <% @cancers.column_names.each do |attr| %>
      
      <button class="toggle-vis" data-column='<%=i.to_s%>'> 
        <%= attr.capitalize %>
      </button>
      <%i += 1%>
      
    <%end%>
  </div>

    <div id="ct_table">
      <table class="display">
        <thead>
          
          <% @cancers.column_names.each do |attr| %>
            
            <th> <%= attr.capitalize %> </th>
            
          <% end %>
          <th>
            Action
          </th>
          
        </thead>

        <tbody>
          <% @cancers.each do |cc| %>
          
            <tr>
              <% @cancers.column_names.each do |attr| %>
                
                <td> 
                  <div class="table_cell"> 
                    <%= cc[attr] %> 
                  </div>
                </td>
              
              <% end %>
              <td>
                <%= link_to 'Show', cancer_path(cc) %>
                <%= link_to 'Delete', cancer_path(cc), method: :delete,
                        data: { confirm: 'Are you sure?' } %>

                <%= link_to 'Edit', edit_cancer_path(cc) %>
              </td>
              
            </tr>
          
          <% end %>
        </tbody>

      </table>
    </div>

    <%= link_to  "Add one cancer type", "/cancers/new" %>

    <%= form_tag import_cancers_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import cancers from csv" %>
    <% end %>
  </section>


  <section id="data_process_admin" class="admin_block">
    <h4>
    Data upload and process
    </h4>
    <%= form_tag({action: :update_samples_num_table_and_reprocessedColumns}, multipart: true) do %>
      <p>
        Generate/Update sample numbers file for cancer types/projects
      </p>
      <%= submit_tag 'Update'%>
    <% end %>

    <%# <%= form_tag({action: :make_analysis_cancer_files}, multipart: true) do 
      <p>
        Make cancers files for different analysis methods
      </p>
      <%= submit_tag 'Generate'
    <% end %>

    <%= form_tag({action: :make_subtype_cancer_files}, multipart: true) do %>
      <p>
        Make cancers files for different subtype methods
      </p>
      <%= submit_tag 'Generate'%>
    <% end %>

    <!--<%= form_tag({action: :update_columns}, multipart: true) do %>
      <p>
        Calculate and update columns for database
      </p>
      <%= submit_tag 'Update'%>
    <% end %>-->
    <%= form_tag({action: :update_columns_cancer}, multipart: true) do %>
      <p>
        Please select the cancer to update columns
      </p>
      <%= select_tag :cancer_id, options_from_collection_for_select(@cancers, :id, :cancer_name, -1) %>
      <br>
      <%= submit_tag 'Submit'%>
    <% end %>

    <%= form_tag({action: :update_files}, multipart: true) do %>
    <p>
        Update files 
    </p>
    <%= submit_tag 'Update'%>
    <% end %>

    <%= form_tag({action: :count_rna_samples}, multipart: true) do %>
    <p>
        count rna samples number (do not click)
    </p>
    <%= submit_tag 'Update'%>
    <% end %>

    </section>

  <hr>
  <br/>

</div>