config/routes.rb
Rails.application.routes.draw do

  get 'debug', to: 'debug#index'
  post 'debug', to: 'debug#add'
  get 'debug/delete/:id', to: 'debug#delete'
  post '/submit/analysis/:str', to: 'submit#handler'
  get '/submit/analyses/:id', to: 'submit#analyses'


  resources :projects do
    resources :samples do
      collection do
        post :import
        post :import_inf_table
      end
      member do
        post :upload_seq
        post :upload_inf
        get :download_seq
        get :download_inf
      end
    end
    collection { post :import}
    collection { post :download_selected_file }
    collection { post :export_selected }
    member { post :download_inf_table}
    member { post :show, format: 'json' }

  end

  resources :samples do
    collection do
      post :make_selected_file
    end
  end

  resources :organs do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :cancers do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :users do
    resources :datasets do
      member { post :upload_file }
      member { get :download_file}
      member { get :download_ds_inf}
      member { get :download_ds_metadata}
      member { post :delete_sample}
    end
  end
  
  root 'welcome#index'

  get 'tutorial', to: 'welcome#tutorial', as: 'tutorial'
  get '/tutorial/database/1', to: "tutorial#database1"
  get '/tutorial/database/2', to: "tutorial#database2"
  get '/tutorial/database/3', to: "tutorial#database3"
  get '/tutorial/database/4', to: "tutorial#database4"


  get '/tutorial/analysis/1', to: "tutorial#analysis1"
  get '/tutorial/analysis/2', to: "tutorial#analysis2"
  get '/tutorial/analysis/3', to: "tutorial#analysis3"
  get '/tutorial/analysis/4', to: "tutorial#analysis4"
  get '/tutorial/mub', to: "tutorial#mub"




  get 'contact', to: 'welcome#contact', as: 'contact'
  get 'docs', to: redirect('docs/index.html')
  get 'terms', to: 'welcome#terms', as: 'terms'

  # read local csv file 
  # get 'data/:name', to: 'raw_files#index'
  get 'api/local', to: 'raw_files#index'
  get 'api/public', to: 'raw_files#public'

  # draw on overview page
  namespace :api do
    resources :analysis, only: [] do
      get 'use_demo', to: 'viz_files#use_demo', as: 'use_demo'
      get 'use_task_output', to: 'viz_files#use_task_output', as: 'use_task_output'
      get 'all_files', to: 'viz_files#all_files', as: 'all_files'
      get 'all_task_outputs', to: 'viz_files#all_task_outputs', as: 'all_task_outputs'
      get 'chosen_files', to: 'viz_files#get_chosen_files', as: 'chosen_files'
      get 'chosen_file_paths', to: 'viz_files#chosen_file_paths', as: 'chosen_file_paths'
      get 'download_demo_file', to: 'viz_files#download_demo_file', as: 'download_demo_file'
      post 'chosen_files', to: 'viz_files#update_chosen_files', as: 'update_chosen_files'
      post 'create_files', to: 'viz_files#create_files', as: 'create_files'
      post 'batch_delete_files', to: 'viz_files#batch_delete_files', as: 'batch_delete_files'
    end
    get "public_file/check_file_exists", to: 'public_file#check_file_exists', as: 'json'
    get 'tabix/:url_name', to: 'tabix_apis#show', as: 'tabix_api'
    get 'public/:url_name', to: 'public_file_apis#show', as: 'public_api'
    get "download_target_file", to: "public_file#download_target_file", as: 'download_target_file'
  end

  # database pages
  get 'database/overview', to: 'database#overview'
  get '/download', to: 'welcome#download'

  get 'user/show', to: 'users#show'
  # get 'demo', to: 'demo#show'
  #post 'welcome/accept_cookies', to: 'welcome#require_cookie'
  post "welcome/require_cookie", to: "welcome#require_cookie", as: "require_cookie"
  
  # visualizer
  scope '/visualizer' do
    # resources :analysis, except: :index
    get 'analysis/:url_name', to: 'analysis#show', as: 'analysis'
  end
  get 'visualizer', to: "analysis#index", as: "visualizer"


  # submit pages
  get "submit/analyses", to: "submit#analyses"
  get "submit/analysesCategory", to: "submit#analysesCategory"
  get "submit/tcrAnalyses", to: "submit#tcrAnalyses"
  get "submit/tcrclub", to: "submit#tcrclub"

  get "submit/pipelines", to: "submit#pipelines"
  get 'submit/job-query/', to: 'submit#query', as: 'query'
  get 'submit/job-query-demo', to: 'submit#query_demo', as: 'query-demo'

  get "submit/job-demo", to: "submit#demo"
  get 'submit/analysis/:id', to: 'submit#index', as: 'submit_analysis'
  get 'submit/pipeline/:id', to: 'submit#pipeline', as: 'submit_pipeline'
  post 'change_dark', to:'application#change_dark'

  post 'query-app-task', to: 'submit#query_app_task', format: 'json'
    post 'query-app-task-dummy', to: 'submit#query_app_task_dummy'
  post 'query-demo-tasks', to: 'submit#query_demo_tasks', format: 'json'
  post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  post 'query-demo-task', to: 'submit#query_demo_task', format: 'json'
  post 'query-all-tasks', to: 'submit#query_all', format: 'json'
  post 'remove-task', to: 'submit#remove_task', format: 'json'

  # get "debug", to: "submit#query_app_task_test"
  # post 'query_app_task_dummy', to: 'submit#query_app_task_dummy'
  # post 'submit_app_task_dummy', to: 'submit#submit_app_task_dummy'
  # post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  # post 'submit-app-task-dummy', to: 'submit#submit_app_task_dummy', format: 'json'

  # admin
  get '/admin', to: 'admin#index', as: "admin_index"
  post "admin/modify_sample_metadata" => "admin#modify_sample_metadata", :as => "admin/modify_sample_metadata"
  post "admin/modify_sample_inf" => "admin#modify_sample_inf", :as => "admin/modify_sample_inf"
  post "admin/update_samples_num_table_and_reprocessedColumns" => "admin#update_samples_num_table_and_reprocessedColumns", :as => "admin/update_samples_num_table_and_reprocessedColumns"
  post "admin/make_analysis_cancer_files" => "admin#make_analysis_cancer_files", :as => "admin/make_analysis_cancer_files"
  post "admin/make_subtype_cancer_files" => "admin#make_subtype_cancer_files", :as => "admin/make_subtype_cancer_files"
  post "admin/update_columns" => "admin#update_columns", :as => "admin/update_columns"
  post "admin/update_files" => "admin#update_files", :as =>"admin/update_files"
  post "admin/count_rna_samples" => "admin#count_rna_samples", :as =>"admin/count_rna_samples"
  post "admin/update_columns_cancer" => "admin#update_columns_cancer", :as => "admin/update_columns_cancer"

  post "admin/modify_viz" => "admin#modify_viz", :as => "admin/modify_viz"
  post "admin/modify_ana_cate" => "admin#modify_ana_cate", :as => "admin/modify_ana_cate"
  post "admin/modify_ana" => "admin#modify_ana", :as => "admin/modify_ana"
  post "admin/modify_viz_source" => "admin#modify_viz_source", :as => "admin/modify_viz_source"
  post "admin/add_img" => "admin#add_img", :as => "admin/add_img"
  post "admin/delete_samples" => "admin#delete_samples", :as => "admin/delete_samples"
  post "admin/update_all_samples" => "admin#update_all_samples", :as => "admin/update_all_samples"
  post "admin/update_all_organs" => "admin#update_all_organs", :as => "admin/update_all_organs"
  post "admin/update_all_cancers" => "admin#update_all_cancers", :as => "admin/update_all_cancers"



  namespace :admin do
    post :update_analysis_category_position, to: 'analysis_categories#update_position'
    resources :analysis_categories, except: :show do
      post :update_position, to: 'analyses#update_position', as: 'update_analysis_position'
      resources :analyses, expect: %i[index show]
    end
    get 'analyses', to: 'analyses#index'
    resources :visualizers
    resources :analysis_pipelines
    resources :tasks, except: :new
    post "clear_outputs", to:"tasks#clear_outputs", as: "clear_outputs"
    post "set_demo_task", to:"tasks#set_demo_task", as: "set_demo_task"
    resources :file_keys, except: :show
    resources :tabix_apis, except: :show
  end

  # serve files
  match 'data/uploads/*path', to: 'raw_files#uploads', as: 'get_uploads', via: :get
  match 'data/demo/*path', to: 'raw_files#demo', as: 'get_demo', via: :get
  match 'data/outputs/*path', to: 'raw_files#outputs', as: 'get_outputs', via: :get
  match 'data/static_viz_data/*path', to: 'raw_files#viz_file', via: :get
  match 'public/data/*path', to: 'raw_files#public_file', via: :get
  match 'public/data/sample_plot/*path', to: 'raw_files#viz_inf_file', via: :get
  get "/database/refreshSelector", to: 'database#refreshSelector'

  post 'query-deepomics', to: 'submit#query_deepomics', format: 'json'
  post 'task-details', to: 'submit#task_details', format: 'json'



end

app/models/project.rb
class Project < ApplicationRecord
  has_many :samples, dependent: :destroy
  validates :project_name, presence: true, uniqueness: { 
    message: ->(object, data) do
      "Project #{data[:value]} already exists. "
    end
  }, on: :create

  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'bom|utf-8') do |row|
      project = find_by_project_name(row['project_name'])|| new
      old_gn = project.num_of_observed_genes
      project.attributes = row.to_hash.slice(*column_names)
      project.num_of_observed_genes = old_gn
      #site = project.primary_site
      ctype = project.cancer_name
      #organ = Organ.find_by(primary_site: site)
      cancer = Cancer.find_by(cancer_name: ctype)
      #project.organ_id = organ.id
      project.cancer_id = cancer.id
      #organ.update_attribute(:num_of_projects, organs.projects.count)
      cancer.update_attribute(:number_of_related_projects, cancer.projects.count)
      project.save!
    end
  end

  def self.to_csv(options={})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |project|
        csv << project.attributes.values_at(*column_names)
      end
    end
  end

  def self.selected_to_csv(project_ids, options={})
    CSV.generate(options) do |csv|
      csv << column_names
      project_ids.each do |id|
        project = Project.find(id)
        csv << project.attributes.values_at(*column_names)
      end
    end
  end

end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
 
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this dataset from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% @attrs.each do |attr| %>
    <% if attr != 'id' && attr != 'created_at' && attr != 'updated_at' %>
      <p> 
        <%= f.label attr.capitalize %> <br>
        <%= f.text_field attr %>
      </p>

    <% end %>
  <% end %>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/projects/edit.html.erb
<% content_for :head do %>
  <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  
  <%= javascript_pack_tag "table_style" %>
<% end %>

<div class="container">
  <h1>Edit Project</h1>
  
  <%= render 'form' %>
  
  <h2>Samples</h2>
  <div id='hidden_helper'>
    Hide columns: 
    <br />
    <% i=0 %>
    <% @sample_attrs.each do |attr| %>
      
        <button class="toggle-vis" data-column='<%=i.to_s%>'> 
          <%= attr.capitalize %>
        </button>
        <%i += 1%>
      
    <%end%>
  </div>


  <table id="Table" class="display">

      <thead>
        <% @sample_attrs.each do |attr| %>
          
            <th> <%= attr.capitalize %> </th>
          
        <% end %>
        <th>Action</th>
      </thead>

      <tbody>
        <% @project.samples.each do |sample| %>
        
          <tr>
            <% @sample_attrs.each do |attr| %>
              
                <td> 
                  <div class="table_cell"> 
                    <%= sample[attr] %> 
                  </div>
                </td>
              
            <% end %>
            
            <td>
              <%= link_to 'Show', project_sample_path(sample.project, sample) %>
              <%= link_to 'Delete', [sample.project, sample],
                method: :delete,
                data: { confirm: 'Are you sure to delete ' + sample.sample_name + '?'} %>
              <%= link_to 'Edit', edit_project_sample_path(sample.project, sample.id) %> 
            </td>
          </tr>
        
        <% end %>
      </tbody>

    </table>
    

  <%= link_to 'create a new sample', new_project_sample_path(@project)%>

  <%= link_to 'Back', "/admin" %>
</div>

app/views/projects/index.html.erb
<% content_for :head do %>
  <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/fixedcolumns/3.3.2/js/dataTables.fixedColumns.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/3.3.2/css/fixedColumns.dataTables.min.css">
  <%= javascript_pack_tag "datatable" %>
<% end %>

<% content_for :title, 'Datasets' %>
<div class="container">
  <div class="mt-5">
    <h1>
    Datasets Information
    <button class = "btn btn-1" style="display:inline" >
      <i class="fas fa-cog"></i>
      <%= link_to "Database Helper", "tutorial/database/1" %>
    </button>
    <button class = "btn btn-1" style="display:inline;" >
    <a href= "https://github.com/deepomicslab/TIMEDB/issues">
      <i class="fas fa-file"></i>
      Report Bug
    </a>
    </button>
    </h1>
  </div>


  <div id="db-toolbar">
    <div class="db-tool-nav">
      <div class="btn btn-outline-dark" data-toggle="collapse" data-target="#hidden_helper" aria-expanded="true" aria-controls="hidden_helper"> 
          Filter Columns <i class="fas fa-caret-down"></i>
      </div>
      <div class="btn btn-outline-dark" data-toggle="collapse" data-target="#download_box" aria-expanded="true" aria-controls="download_box">
        Download Data <i class="fas fa-caret-down"></i>
      </div>
    </div>
    <div id='hidden_helper'  class="db-toolbox collapse p-2">
      <% i=2 %>
      <% @attrs.each do |attr| %>
        <% if attr != 'id'%>
          <% if !@vis.include? attr%>
            <button class="toggle-vis btn btn-outline-secondary" data-column='<%=i.to_s%>'> 
              <%= attr%>
            </button>
          <% end %>
          <%i += 1%>
        <%end%>
      <%end%>
    </div>
    <%= form_tag export_selected_projects_path(format: "csv"), multipart: true do %> 
      <div id="download_box" class="db-toolbox collapse" data-parent="#db-toolbar">
        <div class="form-group p-2">
          <%= button_tag :class => "s_table_sub btn btn-select btn-theme btn-info download" do %>
            <i class='fas fa-check-circle'></i> Selected datasets
          <%end%>
          <%= link_to projects_path(format: "csv"), disabled: true, :class => "s_table_sub btn btn-pink float-right" do %>
            <i class='fas fa-download'></i> All datasets
          <%end%>
        </div>
      </div>
    <%end%>
  </div>
  <br/>



  <%= form_tag export_selected_projects_path(format: "csv"),class:(session[:dark] ? "dark-table mb-5": "mb-5"), multipart: true do %> 
    <%= content_tag :table, role: :datatable, class: "display", id: "table_page", data: { url: projects_path(format: :json)} do %>
      <p>You can click <span style= "color: #006fff;">dataset name</span> to view the original link of dataset.
        You can click <span style= "color: #006fff;">details</span> to view the Sample Details, C1-C6 Subtyping, TIME Estimation.
      </p>
      <thead>
            <th>
              <input type="checkbox" class="selectAll" name="selectAll" value="all">
            </th>
            <% @attrs.each do |attr| %>
              <% if attr=='project_name' %>
                <th>dataset_name</th>
              <% else %>
                <th> <%= attr %> </th>
              <% end %>
              
            <% end %>
            <th>details</th>
      </thead>
      <tbody>
      </tbody>
    <% end %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container">
    <h1> New dataset </h1>
    <%= render 'form' %>
    <%= link_to 'Back', "/admin" %>
</div>

app/views/projects/visualize.html.erb
<% content_for :head do %>
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
<%end%>
<% content_for :title, "Project visualization" %>

<div class = "index-banner">
    <div class = "container">
    <h1 class = "display-4 font-weight-bold">
        Project Overview
    </h1>
    <h2 class = display-4>
        <%= @Project.project_name %>
    </h2>
    </div>
    
</div>
<br>

<h1> Information to be added later </h1> 

<%# this part may be changed later -> text information summary %>

<!-- <div id="head" class="container Block">

    
    <div class="row">
        <div class="col">
            <div class="ov-number">
                11688
            </div>
            <div class="ov-type">
                Samples
            </div>
            
            
        </div>
        <div class="col">
            <div class="ov-number">
                5813
            </div>
            <div class="ov-type">
                Individuals
            </div>
            
            
        </div>

        <div class="col">
            <div class="ov-number">
                54
            </div>
            <div class="ov-type">
                Projects
            </div>
            
           
        </div>

        <div class="col">
            <div class="ov-number">
                29
            </div>
            <div class="ov-type">
                Diseases
            </div>
            
            
        </div>

        <div class="col">
            <div class="ov-number">
                15
            </div>
            <div class="ov-type">
                Countries
            </div>
            
            
        </div>
    </div>
    <br/>
</div>
<div class = "container Block"> 





 to be deleted
<h2>Sample distribution</h2>
<div id = "world-map" class = "container Block"> </div>
</div>
up to here

<br />
<hr />
<section id = "cancer_card">
    <h2>Cancer Type</h2>
    <div class = "container-fluid container">
        <div class = "row cols-xs-space cols-sm-space cols-md-space text-center">            
            <% @cancers.each do |cc| %>
                <% if @singleIcon.include?(cc.cancer_name) %>
                    <div class = "col-lg-2 col-lg-offset-1 mb-4">
                        <%= link_to cc do %>
                            <% if cc.cover_image.blank? %>
                                <%= image_tag "module.jpg", class: "rounded-circle z-depth-2" %>
                            <% else %>
                                <%= image_tag cc.cover_image, class: "rounded-circle z-depth-2" %>
                            <% end %>
                        
                            <%#= image_tag og.primary_site + ".png", class: "rounded-circle z-depth-2" %>
                        <% end %>
                        <h4> <%= cc.cancer_name %> </h4>
                    </div>
                <% end %>
            <% end %>
            <div class = "col-lg-5" > </div>
            <div class = "col-lg-2 col-lg-offset-1 mb-4">
                    
                    <div type="button" class="fa fa-lightbulb-o fa-lg" title="Cancers List" data-toggle="popover" title="" data-content= ' 
                    <%#= render :partial => 'partials/popover' %>
                    <ul>
                    <% @cancers.each do |cc| %>
                        <% if @groupedIcon.include?(cc.cancer_name) %>
                            <li><%= link_to cc.cancer_name, cc %></li>
                        <% end %>
                    <% end %>
                    </ul>
                    '> 
                    <%= image_tag "other.png", class: "rounded-circle z-depth-2" %> 
                    </div> 
                    <h4> Others </h4>

            </div>
            <div class = "col-lg-5" > </div>
        </div>
    </div>
</section>
<hr />

-->



<br />


<%=javascript_pack_tag 'pj-overview-viz'%> 
                        