config/routes.rb
Rails.application.routes.draw do

  get 'debug', to: 'debug#index'
  post 'debug', to: 'debug#add'
  get 'debug/delete/:id', to: 'debug#delete'
  post '/submit/analysis/:str', to: 'submit#handler'
  get '/submit/analyses/:id', to: 'submit#analyses'


  resources :projects do
    resources :samples do
      collection do
        post :import
        post :import_inf_table
      end
      member do
        post :upload_seq
        post :upload_inf
        get :download_seq
        get :download_inf
      end
    end
    collection { post :import}
    collection { post :download_selected_file }
    collection { post :export_selected }
    member { post :download_inf_table}
    member { post :show, format: 'json' }

  end

  resources :samples do
    collection do
      post :make_selected_file
    end
  end

  resources :organs do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :cancers do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :users do
    resources :datasets do
      member { post :upload_file }
      member { get :download_file}
      member { get :download_ds_inf}
      member { get :download_ds_metadata}
      member { post :delete_sample}
    end
  end
  
  root 'welcome#index'

  get 'tutorial', to: 'welcome#tutorial', as: 'tutorial'
  get '/tutorial/database/1', to: "tutorial#database1"
  get '/tutorial/database/2', to: "tutorial#database2"
  get '/tutorial/database/3', to: "tutorial#database3"
  get '/tutorial/database/4', to: "tutorial#database4"


  get '/tutorial/analysis/1', to: "tutorial#analysis1"
  get '/tutorial/analysis/2', to: "tutorial#analysis2"
  get '/tutorial/analysis/3', to: "tutorial#analysis3"
  get '/tutorial/analysis/4', to: "tutorial#analysis4"
  get '/tutorial/mub', to: "tutorial#mub"




  get 'contact', to: 'welcome#contact', as: 'contact'
  get 'docs', to: redirect('docs/index.html')
  get 'terms', to: 'welcome#terms', as: 'terms'

  # read local csv file 
  # get 'data/:name', to: 'raw_files#index'
  get 'api/local', to: 'raw_files#index'
  get 'api/public', to: 'raw_files#public'

  # draw on overview page
  namespace :api do
    resources :analysis, only: [] do
      get 'use_demo', to: 'viz_files#use_demo', as: 'use_demo'
      get 'use_task_output', to: 'viz_files#use_task_output', as: 'use_task_output'
      get 'all_files', to: 'viz_files#all_files', as: 'all_files'
      get 'all_task_outputs', to: 'viz_files#all_task_outputs', as: 'all_task_outputs'
      get 'chosen_files', to: 'viz_files#get_chosen_files', as: 'chosen_files'
      get 'chosen_file_paths', to: 'viz_files#chosen_file_paths', as: 'chosen_file_paths'
      get 'download_demo_file', to: 'viz_files#download_demo_file', as: 'download_demo_file'
      post 'chosen_files', to: 'viz_files#update_chosen_files', as: 'update_chosen_files'
      post 'create_files', to: 'viz_files#create_files', as: 'create_files'
      post 'batch_delete_files', to: 'viz_files#batch_delete_files', as: 'batch_delete_files'
    end
    get "public_file/check_file_exists", to: 'public_file#check_file_exists', as: 'json'
    get 'tabix/:url_name', to: 'tabix_apis#show', as: 'tabix_api'
    get 'public/:url_name', to: 'public_file_apis#show', as: 'public_api'
    get "download_target_file", to: "public_file#download_target_file", as: 'download_target_file'
  end

  # database pages
  get 'database/overview', to: 'database#overview'
  get '/download', to: 'welcome#download'

  get 'user/show', to: 'users#show'
  # get 'demo', to: 'demo#show'
  #post 'welcome/accept_cookies', to: 'welcome#require_cookie'
  post "welcome/require_cookie", to: "welcome#require_cookie", as: "require_cookie"
  
  # visualizer
  scope '/visualizer' do
    # resources :analysis, except: :index
    get 'analysis/:url_name', to: 'analysis#show', as: 'analysis'
  end
  get 'visualizer', to: "analysis#index", as: "visualizer"


  # submit pages
  get "submit/analyses", to: "submit#analyses"
  get "submit/analysesCategory", to: "submit#analysesCategory"
  get "submit/tcrAnalyses", to: "submit#tcrAnalyses"
  get "submit/tcrclub", to: "submit#tcrclub"

  get "submit/pipelines", to: "submit#pipelines"
  get 'submit/job-query/', to: 'submit#query', as: 'query'
  get 'submit/job-query-demo', to: 'submit#query_demo', as: 'query-demo'

  get "submit/job-demo", to: "submit#demo"
  get 'submit/analysis/:id', to: 'submit#index', as: 'submit_analysis'
  get 'submit/pipeline/:id', to: 'submit#pipeline', as: 'submit_pipeline'
  post 'change_dark', to:'application#change_dark'

  post 'query-app-task', to: 'submit#query_app_task', format: 'json'
    post 'query-app-task-dummy', to: 'submit#query_app_task_dummy'
  post 'query-demo-tasks', to: 'submit#query_demo_tasks', format: 'json'
  post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  post 'query-demo-task', to: 'submit#query_demo_task', format: 'json'
  post 'query-all-tasks', to: 'submit#query_all', format: 'json'
  post 'remove-task', to: 'submit#remove_task', format: 'json'

  # get "debug", to: "submit#query_app_task_test"
  # post 'query_app_task_dummy', to: 'submit#query_app_task_dummy'
  # post 'submit_app_task_dummy', to: 'submit#submit_app_task_dummy'
  # post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  # post 'submit-app-task-dummy', to: 'submit#submit_app_task_dummy', format: 'json'

  # admin
  get '/admin', to: 'admin#index', as: "admin_index"
  post "admin/modify_sample_metadata" => "admin#modify_sample_metadata", :as => "admin/modify_sample_metadata"
  post "admin/modify_sample_inf" => "admin#modify_sample_inf", :as => "admin/modify_sample_inf"
  post "admin/update_samples_num_table_and_reprocessedColumns" => "admin#update_samples_num_table_and_reprocessedColumns", :as => "admin/update_samples_num_table_and_reprocessedColumns"
  post "admin/make_analysis_cancer_files" => "admin#make_analysis_cancer_files", :as => "admin/make_analysis_cancer_files"
  post "admin/make_subtype_cancer_files" => "admin#make_subtype_cancer_files", :as => "admin/make_subtype_cancer_files"
  post "admin/update_columns" => "admin#update_columns", :as => "admin/update_columns"
  post "admin/update_files" => "admin#update_files", :as =>"admin/update_files"
  post "admin/count_rna_samples" => "admin#count_rna_samples", :as =>"admin/count_rna_samples"
  post "admin/update_columns_cancer" => "admin#update_columns_cancer", :as => "admin/update_columns_cancer"

  post "admin/modify_viz" => "admin#modify_viz", :as => "admin/modify_viz"
  post "admin/modify_ana_cate" => "admin#modify_ana_cate", :as => "admin/modify_ana_cate"
  post "admin/modify_ana" => "admin#modify_ana", :as => "admin/modify_ana"
  post "admin/modify_viz_source" => "admin#modify_viz_source", :as => "admin/modify_viz_source"
  post "admin/add_img" => "admin#add_img", :as => "admin/add_img"
  post "admin/delete_samples" => "admin#delete_samples", :as => "admin/delete_samples"
  post "admin/update_all_samples" => "admin#update_all_samples", :as => "admin/update_all_samples"
  post "admin/update_all_organs" => "admin#update_all_organs", :as => "admin/update_all_organs"
  post "admin/update_all_cancers" => "admin#update_all_cancers", :as => "admin/update_all_cancers"



  namespace :admin do
    post :update_analysis_category_position, to: 'analysis_categories#update_position'
    resources :analysis_categories, except: :show do
      post :update_position, to: 'analyses#update_position', as: 'update_analysis_position'
      resources :analyses, expect: %i[index show]
    end
    get 'analyses', to: 'analyses#index'
    resources :visualizers
    resources :analysis_pipelines
    resources :tasks, except: :new
    post "clear_outputs", to:"tasks#clear_outputs", as: "clear_outputs"
    post "set_demo_task", to:"tasks#set_demo_task", as: "set_demo_task"
    resources :file_keys, except: :show
    resources :tabix_apis, except: :show
  end

  # serve files
  match 'data/uploads/*path', to: 'raw_files#uploads', as: 'get_uploads', via: :get
  match 'data/demo/*path', to: 'raw_files#demo', as: 'get_demo', via: :get
  match 'data/outputs/*path', to: 'raw_files#outputs', as: 'get_outputs', via: :get
  match 'data/static_viz_data/*path', to: 'raw_files#viz_file', via: :get
  match 'public/data/*path', to: 'raw_files#public_file', via: :get
  match 'public/data/sample_plot/*path', to: 'raw_files#viz_inf_file', via: :get
  get "/database/refreshSelector", to: 'database#refreshSelector'

  post 'query-deepomics', to: 'submit#query_deepomics', format: 'json'
  post 'task-details', to: 'submit#task_details', format: 'json'



end

app/controllers/admin/analyses_controller.rb
class Admin::AnalysesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "timedbccc123456"
  before_action :set_analyses_category, except: :index
  before_action :set_analysis, only: %w(edit update destroy)

  def index
    @analysis_categories = AnalysisCategory.unscoped.order(:position)
  end

  def new
    @analysis = @analysis_category.analyses.new
  end

  def create
    analysis_params[:files_info] = JSON.parse analysis_params[:files_info]
    @analysis = @analysis_category.analyses.build analysis_params

    if @analysis.save
      flash[:success] = "Analysis created."
      redirect_to admin_analyses_path
    else
      flash[:error] = @analysis.errors.full_messages
      render action: 'new'
    end
  end

  def edit

  end

  def update
    p = analysis_params
    begin
      p[:files_info] = JSON.parse p[:files_info]
    rescue
      flash[:error] = 'Please enter a valid JSON string.'
      return render 'edit'
    end

    Rails.logger.debug "[[Debug here]]"
    Rails.logger.debug(p)
    @ana = params[:id]
    @viz = p[:visualizer_ids]
    Rails.logger.debug @viz
    @tmp = 1

    for e in p[:visualizer_ids]
      if e != ""
        Rails.logger.debug e
        @tmp = e
        if AnalysesVisualizers.where(analysis_id: @ana, visualizer_id: e).length == 0
          @relation = AnalysesVisualizers.new(analysis_id: @ana, visualizer_id: e)
          @relation.save!
        end
      end
    end
    Rails.logger.debug p
    if @analysis.update(p)
      flash[:success] = "Analysis updated."
      # Rails.logger.debug(p[:visualizer_id])
      # Rails.logger.debug(params[:id])
      # @relation = AnalysesVisualizers.new(analysis_id: @ana, visualizer_id: @viz)
      # @relation.save!
      redirect_to admin_analyses_path
    else
      flash[:error] = @analysis.errors.full_messages
      redirect_to edit_admin_analysis_category_analysis_path(@analysis_category, @analysis)
    end
  end

  def destroy
    @analysis.destroy
    flash[:success] = "Analysis deleted."
    redirect_to admin_analysis_categories_path
  end

  def update_position
    params[:position].split(',').each_with_index do |id, index|
      Analysis.update id, position: index
    end
  end

  private

  def analysis_params
    p = params.require(:analysis).permit(:name, :url,
              :files_info, :documentation, :about, :references, :multiple_mid, :single_demo_id, :multiple_demo_id, :single_result_id, :multiple_result_id,
              :mid, :analysis_category_id, :hidden, :visualizer_ids => [])
    if !params[:analysis][:image_file].blank?
        p[:cover_image] = "data:image/png;base64," + Base64.strict_encode64(params[:analysis][:image_file].read)
    end
    return p
  end


  def set_analyses_category
    @analysis_category = AnalysisCategory.unscoped.find(params[:analysis_category_id])
  end

  def set_analysis
    @analysis = @analysis_category.analyses.unscoped.find(params[:id])
    # @img_url = "app/assets/images/#{@analysis.mid}.png"
  end

end

app/views/admin/analyses/_form.html.slim
/ - host = Rails.configuration.action_mailer.default_url_options[:host]
- unless @analysis.id.nil?
  = f.association :analysis_category
= f.input :name
= f.input :url, hint: "This name will be embeded in URLs. Hence it must be URL-safe."
= f.association :visualizers, as: :check_boxes
= f.input :mid
= f.input :multiple_mid
= f.input :single_demo_id
= f.input :multiple_demo_id
= f.input :single_result_id
= f.input :multiple_result_id

= f.input :hidden
hr
= f.input :files_info, as: :text, input_html: {value: f.object.files_info_json, data: {'ace': true, 'ace-mode': 'json'}}
= f.input :documentation
= f.input :about
= f.input :references
= f.input :description
hr
= f.error_notification
= f.input :image_file, as: :file
- if !@analysis.cover_image.nil?
  img src = @analysis.cover_image width="400"
hr
= f.button :submit

- content_for :page_script do
  sass:
    textarea.form-control
      height: 200px

- content_for :page_script do
  =javascript_pack_tag 'admin-form'
  sass:
    .ace_editor
      height: 200px
      border: 1px solid #ced4da
      border-radius: 0.25rem

app/views/admin/analyses/edit.html.slim
- content_for :title do
  | Edit Analysis&nbsp;
  = @analysis.name

.container
  ol.breadcrumb
    li.breadcrumb-item
      = link_to 'Analyses', admin_analyses_path
    li.breadcrumb-item = @analysis.name
    li.breadcrumb-item.active Edit
  .card
    .card-body
      h2.card-title
        | Edit Analysis&nbsp;
        = @analysis.name
      hr
      = simple_form_for @analysis, url: admin_analysis_category_analysis_path(@analysis_category, @analysis) do |f|
        = render 'form', f: f

app/views/admin/analyses/index.html.slim
- content_for :title
  | Admin::Analyses

.container
  =render 'partials/admin_navbar'
  .card
    .card-body
      h2.card-title Analyses
    - @analysis_categories.each do |c|
      .card-body.analysis-category-name
        .d-flex
          div
            b
              = icon 'fa', 'folder'
              = c.name
          div.ml-4 style="margin-top:-0.15rem"
            = link_to new_admin_analysis_category_analysis_path(c), class: 'btn btn-sm btn-secondary' do
              = icon 'fas', 'plus'
              | Add Analysis
        - if c.analyses.empty?
          p.text-muted No analysis. Click "Add Analysis" button above to add.
      - unless c.analyses.empty?
        ul.sortable-list.list-group.list-group-flush data-update-path="#{admin_analysis_category_update_analysis_position_path(c)}"
          - c.analyses.unscope(where: :hidden).order(:position).each do |a|
            li.list-group-item.justify-content-between.d-flex data-id="#{a.id}"
              div
                = icon 'fa', 'bars', class: 'drag-handle'
                =  "#{a.name} #{"(#{a.mid})" if !a.mid.blank?}"
                /span.text-muted.ml-2 = "(#{a.js_module_name})"
                - if a.hidden
                  span.text-muted.ml-2
                    = icon 'fas', 'eye-slash', class: 'mr-1'
                    em hidden
              div
                = link_to edit_admin_analysis_category_analysis_path(c, a), class: 'btn btn-sm btn-secondary mr-2' do
                  = icon 'fas', 'edit'
                  | Edit
                -if a.can_be_destroyed
                  = link_to admin_analysis_category_analysis_path(c, a), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} do
                    = icon 'fas', 'trash'
                    | Delete
                - else
                  <button class="btn btn-sm btn-danger disabled" data-toggle="tooltip" data-placement="right"  title="This analysis has active tasks, cannot be deleted">
                    <i class="fas fa-trash"></i>Delete
                  </button>

- content_for :page_script do
  =javascript_pack_tag 'admin-form'

app/views/admin/analyses/new.html.slim
- content_for :title do
  | New Analysis

.container
  nav
    ol.breadcrumb
      li.breadcrumb-item
        = link_to 'Analyses', admin_analyses_path
      li.breadcrumb-item.active New
  .card
    .card-body
      h2.card-title New Analysis
      hr
      = simple_form_for @analysis, url: admin_analysis_category_analyses_path(@analysis_category) do |f|
        = render 'form', f: f